### ISSUE TITLE
Add scripts and docs for maintainers

### ISSUE THREAD

**Issue by anngvu** [gf-dcc/data-model#65]
Go through: https://github.com/gf-dcc/data-model/blob/main/getting_started.md

- [x] @cconrad8 Make sure guide works
- [ ] @cconrad8 Update `scripts/*` and Markdown content for exercise 3 (add option to generate Googlesheet format for template). Resources:
  - https://schematicpy.readthedocs.io/en/latest/cli_reference.html as reference.
  - https://www.datacamp.com/tutorial/how-to-write-bash-script-tutorial
- [x] @anngvu needs to set up more creds (or fill in instructions on how to set up creds) for exercise 4.
- [ ] @cconrad8 Write script for exercise 4.

Also:
- [x] @anngvu Add clarification on running `make`.

**Comment by cconrad8** [comment]
This is super helpful!!! @anngvu thank you i went through the getting started so far and now I need to go through schematic docs.

**Comment by anngvu** [comment]
@cconrad8 I updated script and added more to the [guide doc](https://github.com/gf-dcc/data-model/blob/main/getting_started.md). You may have to pull changes in codespace and rerun the setup creds script again,
