### ISSUE TITLE
Add TypeContraceptiveUse

### ISSUE THREAD

**Issue by anngvu** [gf-dcc/data-model#86]
Optional field to accommodate the ovarian cohort, where it's a relevant clinical covariate. 

Update: This will not necessarily be in CohortCore, it might be in more ovarian-cohort specific template.

**Comment by cconrad8** [comment]
@anngvu I remember mentioning this Tuesday but want to discuss - I'm wondering if we can share one template but utilize dependencies with ovarian and breast
