### ISSUE TITLE
Add separate fields for 'BRCA1 Mutation Pathogenicity' & 'BRCA2 Mutation Pathogenicity'

### ISSUE THREAD

**Issue by anngvu** [gf-dcc/data-model#9]
Note that a generic 'Pathogenicity' property is part of the current HTAN model, with values: "Benign, Likely Benign, Likely Pathogenic, Pathogenic, Uncertain Significance"

Original comment:

> suggest two germline variables, one for BRCA1 and one for BRCA2; values:  pathogenic, likely pathogenic, VUS, negative

Update @cconrad8: To keep it short, this became "classBRCA1" etc.

**Comment by cconrad8** [comment]
Ok thanks - I don't see this on the RFC - 

where does this comment originate from? "suggest two germline variables, one for BRCA1 and one for BRCA2; values: pathogenic, likely pathogenic, VUS, negative"

I think we might want to revisit this term, the word "class" is confusing to me?

**Comment by cconrad8** [comment]
![image](https://github.com/gf-dcc/data-model/assets/114612268/8e41e0bd-3107-458f-bd03-79be072861b8)
I found it - but let me look at what the term that is submitted from the clinical data we have recieved is.

**Comment by anngvu** [comment]
@cconrad8 Would you be able to improve the definition to something better + define the enum this sprint? 

If not, you can reassign to me.
